import React,{useEffect,useRef,useState} from 'react';
import{createRoot}from'react-dom/client';
import{motion,useScroll,useTransform,AnimatePresence}from'framer-motion';
import{ArrowUpRight,Camera,Check,ChevronLeft,ChevronRight,Menu,Sparkles,X,Zap}from'lucide-react';
import'./styles.css';

const booth='/assets/photo-booth.png', event='/assets/event.jpg';
const reveals={hidden:{opacity:0,y:56},show:{opacity:1,y:0,transition:{duration:.8,ease:[.2,.8,.2,1]}}};
const gallery=[
  {src:event,pos:'50% 50%',tag:'Nuntă / București'}, {src:event,pos:'15% 55%',tag:'Private party'},
  {src:booth,pos:'50% 30%',tag:'The booth'}, {src:event,pos:'80% 45%',tag:'Gala night'},
  {src:event,pos:'34% 50%',tag:'After dark'}, {src:event,pos:'66% 50%',tag:'Best people'}
];
const plans=[
 {name:'Essential',price:'1.490',note:'Pentru evenimente intime',items:['3 ore de experiență','Printuri nelimitate','Galerie digitală','Asistent dedicat']},
 {name:'Signature',price:'2.190',note:'Cel mai ales',featured:true,items:['5 ore de experiență','Printuri + GIF + Boomerang','Design personalizat','Recuzită premium','Guestbook inclus']},
 {name:'After Dark',price:'2.990',note:'Experiența completă',items:['Prezență nelimitată','Video confessions','Fundal premium','Album instant','Livrare prioritară']}
];

function Cursor(){const[x,setX]=useState(-100);const[y,setY]=useState(-100);useEffect(()=>{const f=e=>{setX(e.clientX);setY(e.clientY)};addEventListener('pointermove',f);return()=>removeEventListener('pointermove',f)},[]);return <motion.div className="cursor" animate={{x:x-18,y:y-18}} transition={{type:'spring',mass:.08,stiffness:500,damping:28}}/>}
function Nav(){const[open,setOpen]=useState(false);return <><nav><a className="logo" href="#top">LU<span>•</span>MINA</a><div className="navlinks">{['Experiență','Galerie','Recenzii','Pachete'].map(x=><a key={x} href={'#'+x.toLowerCase().replace('ă','a')}>{x}</a>)}</div><a className="pill navcta" href="#contact">Verifică data <ArrowUpRight size={16}/></a><button className="menub" onClick={()=>setOpen(!open)} aria-label="Meniu"><Menu/></button></nav><AnimatePresence>{open&&<motion.div className="mobilemenu" initial={{opacity:0,y:-20}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-20}}>{['Experiență','Galerie','Recenzii','Pachete'].map(x=><a onClick={()=>setOpen(false)} key={x} href={'#'+x.toLowerCase().replace('ă','a')}>{x}</a>)}</motion.div>}</AnimatePresence></>}
function Hero(){const{scrollY}=useScroll();const ty=useTransform(scrollY,[0,900],[0,150]);const scale=useTransform(scrollY,[0,900],[1,1.14]);return <header id="top" className="hero"><div className="noise"/><motion.div className="orb o1" style={{y:ty}}/><motion.div className="orb o2" style={{y:useTransform(scrollY,[0,900],[0,-120])}}/><div className="eyebrow">PHOTO BOOTH / EVENTS / 2026</div><h1><span>YOUR NIGHT.</span><em>AMPLIFIED.</em></h1><motion.div className="hero-booth" style={{y:ty,scale}}><img src={booth}/><div className="ring r1">FUN</div><div className="ring r2">FLASH</div><div className="ring r3">AGAIN</div></motion.div><div className="hero-bottom"><p>Transformăm 3 secunde<br/>în amintirea serii.</p><a className="round" href="#experienta" aria-label="Descoperă"><ArrowUpRight/></a><div className="micro">SCROLL TO<br/>MEET THE BOOTH</div></div></header>}
function Experience(){return <section id="experienta" className="experience"><motion.div variants={reveals} initial="hidden" whileInView="show" viewport={{once:true,amount:.3}}><span className="kicker">01 / EXPERIENȚA</span><h2>Nu este o cabină.<br/><i>Este magnetul serii.</i></h2></motion.div><div className="showcase"><div className="orbit"><img src={booth}/><div className="orbitline l1"/><div className="orbitline l2"/><span className="float f1"><Camera/> DSLR quality</span><span className="float f2"><Zap/> Instant share</span><span className="float f3"><Sparkles/> Studio light</span></div><div className="sidecards left"><article><b>01</b><h3>Intră în cadru</h3><p>Un gest. Un zâmbet. Zero instrucțiuni complicate.</p></article><article><b>02</b><h3>Alege vibe-ul</h3><p>Foto, GIF, boomerang sau mesaj video.</p></article></div><div className="sidecards right"><article><b>03</b><h3>Ia amintirea</h3><p>Print premium și share instant pe telefon.</p></article><article><b>04</b><h3>Privește galeria</h3><p>Toate momentele, într-un singur loc.</p></article></div></div></section>}
function Gallery(){const[active,setActive]=useState(null);return <section id="galerie" className="gallery"><div className="sectionhead"><span className="kicker">02 / GALERIE</span><h2>Proof of <i>good times.</i></h2><p>O selecție demonstrativă. Click pentru experiența lightbox.</p></div><div className="gallerygrid">{gallery.map((g,i)=><motion.button initial={{opacity:0,x:i%2?-60:60}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{duration:.7,delay:(i%3)*.08}} onClick={()=>setActive(i)} key={i} className={'g'+i}><img src={g.src} style={{objectPosition:g.pos}}/><span>{g.tag}<ArrowUpRight size={18}/></span></motion.button>)}</div><AnimatePresence>{active!==null&&<motion.div className="lightbox" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setActive(null)}><button className="close"><X/></button><button className="prev" onClick={e=>{e.stopPropagation();setActive((active+gallery.length-1)%gallery.length)}}><ChevronLeft/></button><motion.img key={active} initial={{scale:.92,opacity:0}} animate={{scale:1,opacity:1}} src={gallery[active].src} style={{objectPosition:gallery[active].pos}}/><button className="next" onClick={e=>{e.stopPropagation();setActive((active+1)%gallery.length)}}><ChevronRight/></button><span>{active+1} / {gallery.length}</span></motion.div>}</AnimatePresence></section>}
function Testimonials(){const data=[['„A fost locul în care s-au întâlnit toți invitații, inclusiv cei care nu se cunoșteau.”','Mara & Vlad','Nuntă / 2026'],['„Fotografiile arată ca din revistă, dar energia a rămas complet naturală.”','Ana Pop','Creative Director'],['„Au venit cu totul pregătit. Noi doar ne-am bucurat de seară.”','Darius M.','Private event']];return <section id="recenzii" className="testimonials"><span className="kicker">03 / VORBE BUNE</span><div className="quote-mark">“</div><div className="reviewrow">{data.map((d,i)=><motion.blockquote key={d[1]} variants={reveals} initial="hidden" whileInView="show" viewport={{once:true}} transition={{delay:i*.12}}><p>{d[0]}</p><footer><b>{d[1]}</b><span>{d[2]}</span></footer></motion.blockquote>)}</div></section>}
function Pricing(){return <section id="pachete" className="pricing"><div className="sectionhead"><span className="kicker">04 / PACHETE</span><h2>Pick your <i>energy.</i></h2><p>Prețurile și conținutul sunt demonstrative și pot fi înlocuite ușor.</p></div><div className="plans">{plans.map((p,i)=><motion.article key={p.name} className={p.featured?'featured':''} initial={{opacity:0,y:50}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.1}}>{p.featured&&<div className="badge">MOST WANTED</div>}<span>{p.note}</span><h3>{p.name}</h3><div className="price"><sup>RON</sup>{p.price}</div><ul>{p.items.map(x=><li key={x}><Check size={16}/>{x}</li>)}</ul><a className="plancta" href="#contact">Alege pachetul <ArrowUpRight/></a></motion.article>)}</div></section>}
function App(){return <><Cursor/><Nav/><main><Hero/><Experience/><Gallery/><Testimonials/><Pricing/><section id="contact" className="contact"><div><span className="kicker">READY WHEN YOU ARE</span><h2>Data ta.<br/><i>Momentul nostru.</i></h2></div><a className="bigcta" href="mailto:hello@lumina.demo">LET'S TALK <ArrowUpRight/></a></section></main><footer className="sitefooter"><a className="logo" href="#top">LU<span>•</span>MINA</a><p>Template demonstrativ pentru o cabină foto premium.</p><div><a href="#">Instagram <Camera size={15}/></a><a href="#">Termeni</a></div><small>© 2026 LUMINA STUDIO</small></footer></>}
createRoot(document.getElementById('root')).render(<App/>);
