import React,{useEffect,useLayoutEffect,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{AnimatePresence,motion}from'framer-motion';
import{gsap}from'gsap';
import{ScrollTrigger}from'gsap/ScrollTrigger';
import{ArrowDown,ArrowUpRight,Camera,Check,ChevronLeft,ChevronRight,Menu,Sparkles,X,Zap}from'lucide-react';
import'./styles.css';
gsap.registerPlugin(ScrollTrigger);
const booth='/assets/photo-booth.png',event='/assets/event.jpg';
const gallery=[['50%','Nuntă / București'],['12%','Private party'],['50%','The booth'],['88%','Gala night'],['35%','After dark']];
const plans=[['Essential','1.490','Pentru evenimente intime'],['Signature','2.190','Cel mai ales'],['After Dark','2.990','Experiența completă']];
function Cursor(){const d=useRef(null),r=useRef(null);useEffect(()=>{let x=0,y=0,rx=0,ry=0,id;const m=e=>{x=e.clientX;y=e.clientY};const t=()=>{rx+=(x-rx)*.14;ry+=(y-ry)*.14;gsap.set(d.current,{x,y});gsap.set(r.current,{x:rx,y:ry});id=requestAnimationFrame(t)};addEventListener('pointermove',m);t();return()=>{removeEventListener('pointermove',m);cancelAnimationFrame(id)}},[]);return <><i ref={d} className="cursor-dot"/><i ref={r} className="cursor-ring"/></>}
function Nav(){const[o,setO]=useState(false);return <><nav><a className="logo" href="#top">LU<span>•</span>MINA</a><div className="navlinks"><a href="#experience">Experiență</a><a href="#gallery">Galerie</a><a href="#reviews">Recenzii</a><a href="#pricing">Pachete</a></div><a className="pill navcta" href="#contact">Verifică data <ArrowUpRight size={16}/></a><button className="menub" onClick={()=>setO(!o)}><Menu/></button></nav><AnimatePresence>{o&&<motion.div className="mobilemenu" initial={{opacity:0,y:-20}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-20}}>{['experience','gallery','reviews','pricing'].map(x=><a key={x} onClick={()=>setO(false)} href={'#'+x}>{x}</a>)}</motion.div>}</AnimatePresence></>}
function Hero(){const root=useRef(null);useLayoutEffect(()=>{const c=gsap.context(()=>{gsap.timeline({scrollTrigger:{trigger:root.current,start:'top top',end:'+=180%',pin:true,scrub:1.1}}).to('.hero-copy-top',{xPercent:-34,opacity:.12},0).to('.hero-copy-bottom',{xPercent:38,opacity:.12},0).fromTo('.hero-booth',{y:'72vh',scale:.42,rotate:-7},{y:'4vh',scale:1,rotate:0,ease:'power2.out'},0).fromTo('.hero-chip.left',{x:'-55vw',rotate:-25},{x:0,rotate:-8},.18).fromTo('.hero-chip.right',{x:'55vw',rotate:30},{x:0,rotate:9},.26).to('.hero-booth',{scale:1.48,y:'7vh'},.62).to('.hero-chip.left',{x:'-42vw',y:'-25vh',rotate:-35},.63).to('.hero-chip.right',{x:'42vw',y:'20vh',rotate:35},.63).to('.hero-flash',{opacity:1,scale:1.3,duration:.06},.89).to('.hero-flash',{opacity:0,duration:.1},.95)},root);return()=>c.revert()},[]);return <header ref={root} id="top" className="hero stage"><div className="hero-glow"/><div className="hero-flash"/><div className="hero-copy"><div className="hero-copy-top">MAKE THE</div><div className="hero-copy-bottom"><i>NIGHT</i> ICONIC.</div></div><div className="hero-booth"><img src={booth}/></div><div className="hero-chip left"><Camera/> STUDIO QUALITY</div><div className="hero-chip right"><Zap/> INSTANT SHARE</div><div className="hero-meta"><span>PHOTO BOOTH EXPERIENCE / 2026</span><span>SCROLL TO ENTER <ArrowDown size={14}/></span></div></header>}
function Experience(){const root=useRef(null);useLayoutEffect(()=>{const c=gsap.context(()=>{const tl=gsap.timeline({scrollTrigger:{trigger:root.current,start:'top top',end:'+=360%',pin:true,scrub:1}});tl.set('.scene-booth',{xPercent:-50,yPercent:-50}).fromTo('.scene-booth',{yPercent:70,scale:.7},{yPercent:-50,scale:1},0).fromTo('.scene-title-a',{xPercent:-120},{xPercent:0},.04).fromTo('.scene-title-b',{xPercent:120},{xPercent:0},.08).to('.scene-title-a',{xPercent:115,opacity:0},.32).to('.scene-title-b',{xPercent:-115,opacity:0},.32).fromTo('.p1',{x:'-65vw',y:'-15vh',rotate:-70},{x:'-24vw',y:'-11vh',rotate:-12},.28).fromTo('.p2',{x:'65vw',y:'15vh',rotate:60},{x:'24vw',y:'14vh',rotate:9},.36).fromTo('.p3',{x:'-60vw',y:'32vh',rotate:40},{x:'-29vw',y:'25vh',rotate:-6},.44).fromTo('.p4',{x:'60vw',y:'-28vh',rotate:-45},{x:'29vw',y:'-24vh',rotate:12},.52).fromTo('.c1',{x:-160,opacity:0},{x:0,opacity:1},.46).fromTo('.c2',{x:160,opacity:0},{x:0,opacity:1},.55).to('.p1,.p3',{x:'-75vw',rotate:-70},.72).to('.p2,.p4',{x:'75vw',rotate:75},.72).to('.callout',{opacity:0,y:-40},.7).to('.scene-booth',{scale:2.8,filter:'brightness(.3) blur(2px)'},.72).fromTo('.final-message',{clipPath:'inset(0 100% 0 0)'},{clipPath:'inset(0 0% 0 0)'},.78)},root);return()=>c.revert()},[]);return <section ref={root} id="experience" className="experience stage"><div className="scene-grid"/><div className="scene-title scene-title-a">ONE BOOTH.</div><div className="scene-title scene-title-b">EVERYBODY IN.</div><div className="scene-booth"><img src={booth}/></div>{[1,2,3,4].map((n)=><div key={n} className={'prop p'+n}><img src={event}/><b>0{n}</b></div>)}<div className="callout c1"><Camera/><b>Cadru perfect</b><span>Lumină de studio, de fiecare dată.</span></div><div className="callout c2"><Sparkles/><b>Fără pauze</b><span>Foto, GIF și print instant.</span></div><div className="final-message">OAMENII FAC<br/><i>MAGIA.</i></div><div className="scene-counter">01 — EXPERIENCE</div></section>}
function Gallery(){const root=useRef(null),[active,setActive]=useState(null);useLayoutEffect(()=>{const c=gsap.context(()=>{const track=root.current.querySelector('.gallery-track');gsap.to(track,{x:()=>-(track.scrollWidth-innerWidth),ease:'none',scrollTrigger:{trigger:root.current,start:'top top',end:()=>'+='+(track.scrollWidth-innerWidth),pin:true,scrub:1,invalidateOnRefresh:true}})},root);return()=>c.revert()},[]);return <section ref={root} id="gallery" className="gallery stage"><div className="gallery-track"><div className="gallery-intro"><span>02 / GALLERY</span><h2>GOOD<br/><i>TIMES.</i></h2><p>Scrollul curge. Momentele rămân.</p></div>{gallery.map((g,i)=><button className="gallery-card" key={i} onClick={()=>setActive(i)}><img src={i===2?booth:event} style={{objectPosition:g[0]}}/><span>0{i+1} — {g[1]}</span></button>)}<div className="gallery-outro">CLICK.<br/>FLASH.<br/><i>KEEP.</i></div></div><AnimatePresence>{active!==null&&<motion.div className="lightbox" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setActive(null)}><button className="close"><X/></button><button className="prev" onClick={e=>{e.stopPropagation();setActive((active+4)%5)}}><ChevronLeft/></button><motion.img key={active} initial={{scale:.88}} animate={{scale:1}} src={active===2?booth:event}/><button className="next" onClick={e=>{e.stopPropagation();setActive((active+1)%5)}}><ChevronRight/></button></motion.div>}</AnimatePresence></section>}
function Reviews(){const root=useRef(null);useLayoutEffect(()=>{const c=gsap.context(()=>{gsap.from('.review-card',{x:(i)=>i%2?-innerWidth:innerWidth,rotate:(i)=>i%2?-8:8,stagger:.12,scrollTrigger:{trigger:root.current,start:'top 75%',end:'center center',scrub:1}})},root);return()=>c.revert()},[]);return <section ref={root} id="reviews" className="reviews"><div className="reviews-head"><span>03 / PEOPLE SAID</span><h2>THEY CAME.<br/><i>THEY POSED.</i></h2></div><div className="review-stack"><article className="review-card"><p>„A fost locul în care s-au întâlnit toți invitații.”</p><b>Mara & Vlad — Nuntă 2026</b></article><article className="review-card dark"><p>„Fotografiile arată ca din revistă, dar energia a rămas naturală.”</p><b>Ana Pop — Creative Director</b></article><article className="review-card violet"><p>„Noi doar ne-am bucurat de seară.”</p><b>Darius M. — Private event</b></article></div></section>}
function Pricing(){return <section id="pricing" className="pricing"><div className="pricing-head"><span>04 / PACKAGES</span><h2>PICK YOUR<br/><i>ENERGY.</i></h2></div><div className="plans">{plans.map((p,i)=><motion.article key={p[0]} className={i===1?'featured':''} initial={{y:140,rotate:i===0?-5:i===2?5:0,opacity:0}} whileInView={{y:0,rotate:0,opacity:1}} viewport={{once:true}} transition={{duration:.8,delay:i*.12}}>{i===1&&<em>MOST WANTED</em>}<small>{p[2]}</small><h3>{p[0]}</h3><div className="price"><sup>RON</sup>{p[1]}</div><ul>{['Printuri nelimitate','Galerie digitală','Design personalizat','Asistent dedicat'].map(x=><li key={x}><Check size={16}/>{x}</li>)}</ul><a href="#contact">Alege pachetul <ArrowUpRight/></a></motion.article>)}</div></section>}
function App(){return <><Cursor/><div className="progress"/><Nav/><main><Hero/><Experience/><Gallery/><Reviews/><Pricing/><section id="contact" className="contact"><div><span>READY WHEN YOU ARE</span><h2>DATA TA.<br/><i>MOMENTUL NOSTRU.</i></h2></div><a href="mailto:hello@lumina.demo">LET'S TALK <ArrowUpRight/></a></section></main><footer><a className="logo" href="#top">LU<span>•</span>MINA</a><p>Template demonstrativ pentru o cabină foto premium.</p><small>© 2026 LUMINA STUDIO</small></footer></>}
createRoot(document.getElementById('root')).render(<App/>);
